config/routes.rb
Rails.application.routes.draw do
  # admin
  namespace :admin do
    root to: "top#index"
    resource :session, only: [ :new, :create, :destroy ]
    resources :organisms, only: [ :destroy ]
  end
  
  root "top#index"
  get 'about', to: "top#about"
  get 'growth', to: "top#growth"
  resources :organisms, only: [ :show, :create ]
end

app/models/administrator.rb
# == Schema Information
#
# Table name: administrators
#
#  id              :integer          not null, primary key
#  login_name      :string(255)      not null
#  hashed_password :string(255)      not null
#  created_at      :datetime         not null
#  updated_at      :datetime         not null
#
# Indexes
#
#  index_administrators_on_login_name  (login_name)
#

class Administrator < ActiveRecord::Base
end

app/models/organism.rb
# == Schema Information
#
# Table name: organisms
#
#  id                   :integer          not null, primary key
#  content_type         :string(255)
#  data                 :binary(16777215)
#  description          :text(65535)
#  micromotion_degree   :integer          default(90), not null
#  step_length          :integer          default(50), not null
#  multiplication_speed :integer          default(5), not null
#  created_at           :datetime         not null
#  updated_at           :datetime         not null
#

require 'rmagick'
class Organism < ActiveRecord::Base
  attr_reader :uploaded_image
  attr_accessor :uploaded_image, :destroy_flag
  
  IMAGE_TYPES = { "image/jpeg" => "jpg", "image/gif" => "gif",
    "image/png" => "png" }
  
  validates :data, :content_type, presence: true
  validate :check_image
  
  def uploaded_image=(image)
    content_type = convert_content_type(image.content_type)
    image_title = image.original_filename
    extension  = File.extname(image_title)
    if content_type == "application/octet-stream"
      if extension.match(/.jpg/i)
        self.content_type = "image/jpeg"
      elsif extension.match(/.png/i)
        self.content_type = "image/png"
      elsif extension.match(/.gif/i)
        self.content_type = "image/gif"
      else
        self.content_type = convert_content_type(image.content_type)
      end
    else
      self.content_type = convert_content_type(image.content_type)
    end
    img = Magick::Image.from_blob(image.read).shift
    if img.columns == img.rows
      img = img.resize_to_fit(100, 100)
    elsif img.columns > img.rows
      img = img.resize_to_fit(100, 10000)
    else
      img = img.resize_to_fit(10000, 100)
    end
    self.data = img.to_blob
    @uploaded_image = image
  end
  
  def extension
    IMAGE_TYPES[content_type]
  end
  
  private
  def convert_content_type(ctype)
    ctype = ctype.rstrip.downcase
    case ctype
    when "image/pjpeg" then "image/jpeg"
    when "image/jpg" then "image/jpeg"
    when "image/x-png" then "image/png"
    else ctype
    end
  end

  def check_image
    if @uploaded_image
      if data.size > 5.megabytes
        errors.add(:uploaded_image, :too_big_image)
      end
      unless IMAGE_TYPES.has_key?(content_type)
        errors.add(:uploaded_image, :invalid_image)
      end
    end
  end
end

app/controllers/admin/base.rb
class Admin::Base < ApplicationController
  before_action :authorize_admin
  layout "admin"

  private
  def authorize_admin
    unless current_admin
      redirect_to :root; return false
    end
  end
end

app/controllers/admin/organisms_controller.rb
class Admin::OrganismsController < Admin::Base
  def destroy
    @organism = Organism.find(params[:id])
    @organism.destroy
    flash.notice = "削除しました。"
    redirect_to :admin_root
  end
end

app/controllers/admin/sessions_controller.rb
class Admin::SessionsController < Admin::Base
  skip_before_action :authorize_admin
  
  def new
    if current_admin
      redirect_to :admin_root
    else
      @form = LoginForm.new
      render action: 'new'
    end
  end
  
  def create
    @form = LoginForm.new(params[:login_form])
    if @form.login.present?
      administrator = Administrator.find_by_login_name(@form.login)
    end
    if Admin::Authenticator.new(administrator).authenticate(@form.password)
      session[:administrator_id] = administrator.id
      flash.notice = "ログインしました。"
      redirect_to :admin_root
    else
      flash.now[:alert] = "ログインに失敗しました。"
      render action: 'new'
    end
  end
  
  def destroy
    session.delete(:administrator_id)
    flash.notice = "ログアウトしました。"
    redirect_to :admin_root
  end
end

app/controllers/admin/top_controller.rb
class Admin::TopController < Admin::Base
  skip_before_action :authorize_admin, only: [ :index ]
  def index
    redirect_to :new_admin_session unless current_admin
    @organisms = Organism.order('id desc')
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  def current_admin
    if session[:administrator_id]
      @current_admin ||= Administrator.find_by(id: session[:administrator_id])
    end
  end
  helper_method :current_admin
end

app/controllers/organisms_controller.rb
class OrganismsController < ApplicationController
  def show
    @organism = Organism.find(params[:id])
    send_image if params[:format].in?(["jpg", "png", "gif"])
  end
  
  def create
    if params[:uploaded_image].present?
      @organism = Organism.new
      @organism.uploaded_image = params[:uploaded_image]
      if @organism.save!
        host = request.host + (Rails.env.development? ? ":3000" : "")
        render json: [ @organism.id, @organism.extension,
          @organism.micromotion_degree, @organism.step_length, @organism.multiplication_speed ]
      else
        render json: [ 'error' ]
      end
    else
      render json: [ 'error' ]
    end
  end

  private
  def send_image
    if @organism.data.present?
      data = @organism.data
      img = Magick::Image.from_blob(data).shift
      send_data img.to_blob,
        type: @organism.content_type, disposition: "inline"
    else
      raise NotFound
    end
  end
end

app/controllers/top_controller.rb
class TopController < ApplicationController
  def index
  end
  
  def growth
    @organisms = [ Organism.where(description: 'euglena').first ].compact #Organism.order('id desc')
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  include HtmlBuilder
  def page_title
    title = "Euglena (ユーグレナ)"
    title = @title + " - " + title if @title
    title
  end
  
  # 改行文字 => BR
  def hbr(target)
    target = html_escape(target)
    target.gsub(/\r\n|\r|\n/, "<br />").html_safe
  end
  
  # flash
  def flash_messages
    markup do |m|
      m.div(flash[:alert], class: 'alert alert-danger', role: 'alert') if flash[:alert].present?
      m.div(flash[:notice], class: 'alert alert-info', role: 'alert') if flash[:notice].present?
    end
  end
  
  # エラーメッセージの表示
  def translate_field_name(form, field)
    t(field, scope: [ :activerecord, :attributes, form.object.class.to_s.underscore ])
  end

  def format_error_message(model, field, form)
    messages = model.errors[field]
    messages = [ messages ].flatten
    text = raw('')
    messages.each do |message|
      text << content_tag(:p,
        translate_field_name(form, field) + ' ' + message,
        class: "error_message")
    end
    text
  end
  
  def organism_image_tag(organism, options = {})
    if organism.data.present?
      path = organism_path(organism, format: organism.extension)
      image_tag(path, { alt: 'organism_image' }.merge(options))
    end
  end
end

app/views/admin/shared/_header.html.erb
<div class="navbar navbar-default navbar-static-top header-navbar mb10">
  <h1 class="ma0">
    <%= link_to "Euglena Admin", :root, :class => "navbar-brand" %>
  </h1>
  <a class="btn btn-navbar navbar-toggle mr15 ml0" data-toggle="collapse" data-target=".navbar-collapse"
    style="background: #43af34 !important; border: none;">
    <span class="icon-bar" style="background: #DDD;"></span>
    <span class="icon-bar" style="background: #DDD;"></span>
    <span class="icon-bar" style="background: #DDD;"></span>
  </a>
  <div class="navbar-float-clear clear"></div>
  <div class="navbar-collapse collapse navbar-responsive-collapse" >
    <ul class="nav navbar-nav">
      <li><%= link_to fa_icon('sign-out', text: 'ログアウト'), [ :admin, :session ], method: :delete,
                data: { confirm: '本当にログアウトしますか?' } if current_admin %></li>
    </ul>
  </div>
</div>

app/views/admin/top/index.html.erb
<div id="AdminOrganismsArea">
  <% @organisms.each do |organism| %>
    <div class="box">
      <%= organism_image_tag(organism) %>
      <p class="text-center mt5">
        <%= content_tag(:a, '削除'.html_safe, href: admin_organism_path(organism),
          data: { method: :delete, confirm: "本当に削除してよろしいですか?" },
          :class => 'btn btn-default btn-danger', role: 'button') %>
      </p>
    </div>
  <% end %>
</div>

app/views/layouts/admin.html.erb
<!DOCTYPE html>
<html lang="ja" xmlns="http://www.w3.org/1999/xhtml">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1">
    <meta name="viewport" content="width=device-width">
    <title><%= page_title %></title>
    <%= stylesheet_link_tag 'application', media: 'all' %>
    <%= javascript_include_tag 'application' %>
    <%= favicon_link_tag %>
    <%= csrf_meta_tags %>
  </head>
  <body>
    <%= render "admin/shared/header" %>
    <div class="container">
      <div class="row">
        <div class="col-xs-12">
          <%= flash_messages %>
          <%= yield %>
        </div>
      </div><!--/row-->
      <%= render 'shared/footer'%>
    </div> <!-- /container -->
  </body>
</html>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="ja" xmlns="http://www.w3.org/1999/xhtml">
<head>
  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1">
  <meta name="viewport" content="width=device-width">
  <title><%= page_title %></title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
  <%= render "shared/tracking" if Rails.env.production? %>
  
  <meta name="keywords" content="Euglena,ユーグレナ,ミドリムシ,増殖,アプリ,楽しい" />
  <meta name="description" content="Euglenaはミドリムシを始め、自分でアップロードした生物を楽しく増殖させることができるwebアプリです。" />
  <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1">
  <meta property="og:title" content="生き物の増え方を体験する　- Euglena" />
  <meta property="og:description" content="Euglenaはミドリムシを始め、自分でアップロードした生物を楽しく増殖させることができるwebアプリです。" />
  <meta property="og:image" content="<%= image_url('background.jpg', only_path: false) %>"/>
  <meta property="og:url" content="<%= request.url %>"/>
  <meta property="og:type" content="website"/>
  <meta property="og:site_name" content="Euglena"/>
</head>
<% before_authentication = controller.controller_name == 'top' && controller.action_name == 'index' %>
<body id="<%= 'before_authentication' if before_authentication %>" data-growth-count="<%= request.smart_phone? ? 25 : 50 %>">
  <%= render "shared/header" unless before_authentication %>
  <div id="container" style="<%= 'margin: 0;' if before_authentication %>">
    <%= flash_messages %>
    <%= yield %>
  </div>
  <%= render 'shared/footer'%>
</body>
</html>

app/views/shared/_flash.html.erb
<div id="flash">
  <div id="flash_alert" style="<%= flash.present? ? '' : 'display: none;' %>">
    <%= flash.alert if flash.present? %>
  </div>
</div>

app/views/shared/_footer.html.erb
<div id="footer">
  <p class="tac fs12">
    &copy; <%= Time.now.year %> <%= link_to 'Takuya Okuhara', 'https://twitter.com/takuya_okuhara' %> All Rights Reserved.
  </p>
</div>

app/views/shared/_header.html.erb
<div class="navbar navbar-default navbar-static-top header-navbar mb10">
  <h1 class="ma0">
    <%= link_to "Euglena", :root, :class => "navbar-brand" %>
  </h1>
  <a class="btn btn-navbar navbar-toggle mr15 ml0" data-toggle="collapse" data-target=".navbar-collapse"
    style="background: #43af34 !important; border: none;">
    <span class="icon-bar" style="background: #DDD;"></span>
    <span class="icon-bar" style="background: #DDD;"></span>
    <span class="icon-bar" style="background: #DDD;"></span>
  </a>
  <div class="navbar-float-clear clear"></div>
  <div class="navbar-collapse collapse navbar-responsive-collapse" >
    <ul class="nav navbar-nav">
      <li><%= link_to fa_icon('question-circle', text: 'Euglenaとは'), :about %></li>
      <li>
        <a href="http://www.facebook.com/share.php?u=https://euglena.herokuapp.com" onclick="window.open(encodeURI(decodeURI(this.href)), 'FBwindow', 'width=554, height=470, menubar=no, toolbar=no, scrollbars=yes'); return false;" rel="nofollow">
          <%= fa_icon('facebook-official', text: 'Facebook シェア') %>
        </a>
      </li>
      <li>
        <a href="http://twitter.com/share?text=%e8%87%aa%e5%88%86%e3%81%ae%e5%a5%bd%e3%81%8d%e3%81%aa%e7%94%9f%e3%81%8d%e7%89%a9%e3%81%8c%e5%a2%97%e3%81%88%e3%81%a0%e3%81%99%ef%bc%81%ef%bc%9f%e7%94%9f%e7%89%a9%e3%81%ae%e6%96%b0%e3%81%97%e3%81%84%e5%ad%a6%e3%81%b3%e3%81%ae%e5%bd%a2%e3%80%82Euglena%20%28%e3%83%a6%e3%83%bc%e3%82%b0%e3%83%ac%e3%83%8a%29%20by%20@takuya_okuhara&url=https://euglena.herokuapp.com"
          onClick="window.open(encodeURI(decodeURI(this.href)), 'tweetwindow',
          'width=650, height=470, personalbar=0, toolbar=0, scrollbars=1, sizable=1');return false;" rel="nofollow">
          <%= fa_icon('twitter', text: 'Twitter シェア') %>
        </a>
      </li>
    </ul>
  </div>
</div>

app/views/top/about.html.erb
<div style="clear: both"></div>
<div class="col-xs-12 col-md-offset-2 col-md-10">
  <h2>Euglenaとは</h2>
  <div style="padding: 10px 20px;">
    <p>生命は繋がっています。</p>
    <p>ヒトが受精卵という一つの細胞から細胞分裂を繰り返して形作られるのと同様に、</p>
    <p>目に見えない微生物たちも、自らを分裂させることで子孫を残しています。</p>
    <p>「Euglena」はミドリムシを意味し、ミドリムシの分裂を通して直感的に生命のバトントスを感じることができます。</p>
    <p>ミドリムシ以外にも自分の好きな生き物を追加することで増殖させることができます。</p>
  </div>
</div>

app/views/top/growth.html.erb
<div id="AddOrganismsArea">
  <div id="AddOrganismImageLoader" class="box">
    <p class="add_button"><%= fa_icon('plus') %></p>
    <%= image_tag('image_loader.gif', class: 'loader') %>
  </div>
  <div id="OrganismsArea">
    <% @organisms.each do |organism| %>
      <div class="box organism_box" data-image-url="<%= organism_path(organism, format: organism.extension) %>">
        <%= organism_image_tag(organism, 'data-micromotion-degree' => organism.micromotion_degree,
          'data-step-length' => organism.step_length, 'data-multiplication-speed' => organism.multiplication_speed) %>
      </div>
    <% end %>
  </div>
  <p id="ToggleAddOrganismsArea"><%= fa_icon('angle-down') %></p>
  <p id="ResetGrowthSpace">リセット</p>
  <%= form_tag '' do %>
    <%= file_field_tag 'uploaded_image', style: 'display: none; position: absolute;
      top: -500000px; left: -500000px;' %>
  <% end %>
</div>
<div id="GrowthSpace">
  <%= image_tag('euglena.png', class: 'organism origin', style: '', 'data-micromotion-degree' => '90',
    'data-step-length' => '50', 'data-multiplication-speed' => '5') %>
</div>

app/views/top/index.html.erb
<div id="TopPage">
  <h1 class="main_txt">Life in WEB</h1>
  <h4 class="sub_txt">生命を感じよう</h4>
  <%= content_tag(:a, 'Start',
    href: growth_path, :class => 'btn btn-default btn-primary', role: 'button') %>
</div>